dist: xenial
language: go
go:
  - 1.11.x

sudo: required

before_install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip
  - sudo mv include/* /usr/include/
  - sudo mv bin/* /usr/bin/
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 245caced2b16358b1c5e267691b17e9ee9952127 && go install && cd -
  - glide install
script:
  - make
  - make test