dist: xenial
language: go
go:
  - 1.13.x

sudo: required

before_install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip
  - sudo mv include/* /usr/include/
  - sudo mv bin/* /usr/bin/
  - sudo chmod +x /usr/bin/protoc
install:
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v1.8.5
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get -u github.com/golang/protobuf/protoc-gen-go
script:
  - make
  - make test