version: '3'
services:
  pubsub:
    ports:
      - "8085:8085"
    image: google/cloud-sdk:178.0.0
    command: "gcloud beta emulators pubsub start --verbosity=debug"
  cdb:
    ports:
      - "26257:26257"
    image: "cockroachdb/cockroach:v1.0.6"
    command: "start --insecure --host=0.0.0.0"
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    image: "rabbitmq:management"
