# Example and test config.
rabbitmq:
  enabled: true
  hosts:
    - amqp://localhost
    - amqp://localhost
  queue: "sheep"
  
cockroachdb:
  enabled: false

spanner:
  enabled: true
  project: test
  instance: sheep-test
  database: test