# Example and test config.
rabbitmq:
  enabled: true
  hosts:
    - amqp://localhost
    - amqp://localhost
  queue: "sheep"
  
cockroachdb:
  enabled: true
  host: localhost
  username: root
  port: 26257
  sslmode: disable
  dbname: sheep

pubsub:
  enabled: false

spanner:
  enabled: false
  project: test
  instance: sheep-test
  database: test