# Example and test config.
master: true
worker: true
# When in direct mode, the master will write
# directly to the database.
direct: false
# Log Level
level: debug

service:
  port: 5309
  rest: 8080

rabbitmq:
  enabled: false
  hosts:
    - amqp://localhost
    - amqp://localhost
  queue: "sheep"
  
cockroachdb:
  enabled: false
  host: localhost
  username: root
  port: 26257
  sslmode: disable
  dbname: sheep

pubsub:
  enabled: true
  project: jinked-home
  topic: sheep

spanner:
  enabled: true
  shards: 10 # Shard writes on a per-counter basis out to this many buckets.
             # This helps with hot writes (but not reads, use a cache).
  project: jinked-home
  instance: sheep-test
  database: sheep