# Example and test config.
rabbitmq:
  enabled: false
  hosts:
    - amqp://localhost
    - amqp://localhost
  queue: "sheep"
  
cockroachdb:
  enabled: false
  host: localhost
  username: root
  port: 26257
  sslmode: disable
  dbname: sheep

pubsub:
  enabled: true
  project: jinked-home
  topic: sheep

spanner:
  enabled: true
  project: jinked-home
  instance: sheep-test
  database: test